
-- create db
CREATE DATABASE jytuser;

-- create user
CREATE USER JYT WITH PASSWORD '3atnF?QFG8gE}nK';

-- create schema and set ownership
CREATE SCHEMA IF NOT EXISTS JYT;
ALTER SCHEMA JYT OWNER TO JYT;

-- set default search_path to user
ALTER USER JYT SET search_path TO JYT;

-- grant permissions to user
REVOKE ALL ON DATABASE postgres FROM JYT;
REVOKE ALL ON DATABASE jytuser FROM JYT;
REVOKE ALL ON SCHEMA JYT FROM JYT;
GRANT CONNECT ON DATABASE jytuser TO JYT;
GRANT CREATE ON DATABASE jytuser TO JYT;
GRANT INSERT ON ALL TABLES IN SCHEMA JYT TO JYT;
GRANT UPDATE ON ALL TABLES IN SCHEMA JYT TO JYT;
GRANT DELETE ON ALL TABLES IN SCHEMA JYT TO JYT;
GRANT SELECT ON ALL TABLES IN SCHEMA JYT TO JYT;
ALTER DEFAULT PRIVILEGES IN SCHEMA JYT GRANT SELECT ON TABLES TO JYT;

